name: git_stat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  path_provider: ^2.1.5
  shared_preferences: ^2.3.3
  motion_tab_bar: ^2.0.4
  loading_animation_widget: ^1.3.0
  shimmer: ^3.0.0
  http: ^1.2.2
  google_fonts: ^6.2.1
  flutter:
    sdk: flutter
  intl: ^0.19.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
